bowler/query.py
bowler/tests/smoke-target.py
bowler/tests/smoke.py
bowler/tool.py

Fixes #1 by moving the fixer generation from the `compile()` method to
a separate `create_fixer()` method, so that the bound transform is
preserved correctly.

Fix query pipeline for multiple transforms

---

docs/api-query.md

This is to solve https://github.com/facebookincubator/Bowler/issues/4
I *assume* there was an API change and the documentation wasn't updated. 
I also assume that the intention was to change a function name.
Also, when running `make lint` I got changes for `bowler/tests/smoke-target.py`, which I think should be fixed in another PR.

[docs/api-query] select_name -> select_function

---

bowler/query.py
docs/api-selectors.md

Change the `.select_method()` and `.select_function()` selectors to
allow selection of methods/functions with multiple decorators.
Before this change only the `funcdef` node will be selected, but now the entire `decorated` node is selected.
```foo.py
@test_decorator
@some_other_decorator
def foo():
pass
```

Let selectors match methods/functions with multiple decorators

---

bowler/query.py

The selectors for function/method calls did not account for the
'await' keyword in the grammar for power elements, preventing Bowler
from correctly matching and modifying awaited coroutines.  This
adds the generic, optional `TOKEN` element to the selectors to match
those keywords when used.

Fix #6: Match await keyword in select_function/method

---

bowler/main.py
bowler/tool.py
docs/basics-setup.md

**Primarily close #16**. Using print statements for debugging I narrowed the difference in logical flow for files with & without a newline terminator to ``refactor_string()`` imported from ``fissix``, where a ``NoneType`` 'tree' passes silently.
**Additionally**:
* The ``--version`` option did not work for me. This seems to fix it.
* There's a typo in the docs under 'Setup -> Installing Bowler'
*  ~~As cloned, I was unable to set-up the virtual env because of the use of ``source`` in the makefile. ``.`` instead worked & is standardised so perhaps consider changing to this? I'm happy to revert this aspect of the PR, though.~~

Accept files with no trailing newline + minor revisions

---

bowler/__init__.py
bowler/__main__.py
bowler/helpers.py
bowler/imr.py
bowler/main.py
bowler/query.py
bowler/tests/__init__.py
bowler/tests/query.py
bowler/tests/smoke-target.py
bowler/tests/smoke.py
bowler/tool.py
bowler/types.py
website/static/css/custom.css

Sets all python files to contain both a python3 shebang and the standard Facebook copyright header.

Fix copyright headers

---

bowler/tests/__init__.py
bowler/tests/tool.py
bowler/tool.py

This should solve[ issue 19](https://github.com/facebookincubator/Bowler/issues/19) by adding all the hunks at once. 
I stripped out the name of the file (the --- filename +++ filename) from the top of each hunk, and created one giant bytestring with the hunks all combined. 
`make lint test` passes.

Applies hunks in single patch call

---

bowler/main.py

```
(.venv) darwin ~/src/Bowler git:ipython-fix ✓ $ bowler do
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> Query
<class 'bowler.query.Query'>
>>> ^D
now exiting InteractiveConsole...
(.venv) darwin ~/src/Bowler git:ipython-fix ✓ $ pip install ipython -q
(.venv) darwin ~/src/Bowler git:ipython-fix ✓ $ bowler do
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: Query
Out[1]: bowler.query.Query
```
tests appear to pass
```
(.venv) darwin ~/src/Bowler git:ipython-fix ✓ $ make lint test
black --check bowler …
```

If IPython is unavailable, default to regular interpreter.

---

bowler/tests/smoke.py
makefile
setup.py

Fixes make format to run isort first (with proper arguments and auto-application), and then run black afterwards for final cleanup.

Apply isort with appropriate arguments before running black

---

bowler/helpers.py
bowler/tool.py

Show human-visible log lines on failure to process a file:
```
$ bowler run u.py missing
ERROR:bowler.tool:Skipping missing: failed to read because [Errno 2] No such file or directory: 'missing'
```
and human-readable names for tokens.
```
Old:
[file_input] ""
.  [funcdef] ""
.  .  [1] "" "def"
.  .  [1] " " "f"
.  .  [parameters] ""
.  .  .  [7] "" "("
.  .  .  [1] "" "x"
.  .  .  [8] "" ")"
New:
[file_input] ''
.  [funcdef] ''
.  .  [NAME] '' 'def'
.  .  [NAME] ' ' 'f'
.  .  [parameters] ''
.  .  .  [LPAR] '' '('
.  .  .  [NAME] '' 'x'
.  .  .  [RPAR] '' ')'
```

Improve usability

---

bowler/helpers.py
bowler/main.py
bowler/query.py

This doesn't have a test, but regular dump doesn't either.  This is intended for extremely short snippets, like `def x(n): pass` or `x/2` to then replace some pieces with `any` or `any+`.  Are there cases I'm missing that this won't work?

Add --match to dump, which shows the form used for matching patterns.

---

bowler/helpers.py
bowler/tests/__init__.py
bowler/tests/type_inference.py
bowler/type_inference.py
makefile
setup.py

The rationale for this is when your refactoring script depends on arguments
being of a certain (known) type in order to do the automated refactor,
otherwise letting a human review it.  This isn't perfect, but it's pretty close
for most common Python.
Closes #41

Add numeric type inference along with simple tests.

---

bowler/main.py
bowler/tool.py

Bowler allows clients to provide their own filters and modifier functions.  During development of these functions, it is helpful to use pdb/ipdb to step into these functions inspect the nodes/capture variables and accordingly write up rules.
Since, bowler by default uses in_process=False, using debug statements in these functions ends up in exiting the program (since the program is confused about stdout/stderrs.) 
By, setting the IN_PROCESS attribute in debug mode, the clients can use pdb/ipdb statements while developing with `bowler`.

Enable debugging while using bowler

---

bowler/query.py
bowler/tests/query.py

this is an attempt at fixing #46 
I'm new to AST and my understanding of how bowler works is quite limited, so this PR might not be the "right solution" - still, it has fixed the problem in the cases that mattered to me.
Happy to improve following your suggestions.

fix renaming of modules, when nesting of import paths changes

---

bowler/tool.py

This change lets us know the number of files, but does mean that we
completely populate the queue before any chance of taking work off of
it.  (The queue size is unbounded, and this means we can't switch to a
bounded one.)
Fixes #69

Don't start processes until after refactor_dir.

---

bowler/__init__.py
bowler/query.py
bowler/tests/__init__.py
bowler/tests/query.py

Previously Query("foo.py").select_module("a.b").rename("x.y.z") would
change `a.b.func()` to `x.y.func()`. Make sure that rename() handles
`power` properly source and destination having different lengths
Note, this does not fix two issues:
- If someone shadows an import, we can't detect that right now. That requires a stateful visitor, unfortunately.
- There was a kludge added to this method because `module_access` and `module_name` refer to the same underlying node. Without the kludge, we'd end up modifying the same name twice. If there's a better way to handle this, feel free to suggest. I don't think checking if the node is changed is sufficient, because it might be marked changed from modifying a child node. Also, I can't use a set here because Node/Leaf doesn't have a hash.

Handle renaming modules to names of different lengths.

---

bowler/__init__.py
bowler/imr.py
bowler/main.py
bowler/query.py
bowler/tests/__init__.py
bowler/tests/smoke.py
bowler/tool.py
bowler/types.py

After running all transforms on a file, this validates that the
resulting file can be parsed by the AST module.  For files with bad
syntax or other errors, generate a useful error message on stderr, and
skip processing those hunks.  Also tracks the exceptions generated, and
builds a list of all exceptions on the Query object, so they can be
tracked and/or inspected after the query is executed.

Validate AST of transformed files

---

bowler/imr.py
bowler/query.py

Allows function argument modifiers to work without needing filters, and improves the function selector to also match imports.

Improvements to function refactoring

---

CHANGELOG.md
bowler/tests/tool.py
bowler/tool.py

Because ast is from the host python, it rejects all kinds of valid (to some
version of Python) syntax that we might not even have modified in the
transform.  This uses fissix, which I believe is strict enough to catch the
typical errors like mismatched parens, extra commas, or bad indentation.
Fixes #77

Switch validation to use fissix instead of ast.

---

bowler/tool.py

Previously, Bowler's error logging was not partiuclarly helpful, e.g.:
```
ERR:tool.py:216  Skipping t.py: failed to transform because
ERR:tool.py:118  AssertionError:
```
With this patch, it includes the full traceback:
```
ERR:tool.py:219  Skipping t.py: failed to transform because
Traceback (most recent call last):
File "/Users/andy/forks/Bowler/bowler/tool.py", line 209, in refactor_queue
hunks = self.refactor_file(filename)
File "/Users/andy/forks/Bowler/bowler/tool.py", line 171, in refactor_file
tree = self.refactor_string(input, filename)
File "/Users/andy/.virtualenvs/tmp-4d43f26bfaec7fd/lib/python3.7/site-packages/fissix/refactor.py", line 370, in refactor_string
self.refactor_tree(tree, name)
File "/Users/andy/.virtualenvs/tmp-4d43f26bfaec7fd/lib/python3.7/site-packages/fissix/r …
```

Log the full traceback in errors

---

bowler/main.py

Fix #49: Since retcode will always be an integer 0 or 1 this was always bound to fail.
@jreese I checked there weren't any errors while running query, but as you said all instances weren't replaced Can it be because of not matching with the Pattern?

Don't compare retcode with 'None'

---

.github/workflows/build.yml
bowler/tests/lib.py
bowler/tests/tool.py
bowler/tool.py
makefile
requirements-dev.txt
requirements.txt
scripts/check_copyright.sh

* Switch to using my [`moreorless` library](https://github.com/thatch/moreorless), which is capable of diffing and patching including "No newline at eof" cross-platform.  No longer saves reject files.  I don't know how that would have been possible to begin with if we're only picking and choosing hunks, rather than editing them (or the original sources change out from under us).  Only modifies the file after a successful patch.
* Several build/test related fixes
* enable tests on windows and 3.8, run on branches that start with "tmp-" too
* force in_process mode on Windows and more recent Python (this could probably be more nuanced, but this works at the expense of it being single-threaded).  I'm also not 100% sure of the conditions here; can we detect if the multiprocessing start method …

Stop shelling out to patch

---

bowler/query.py
bowler/tests/lib.py
bowler/tests/query.py
bowler/tool.py
docs/api-query.md

fixes #119 
this allows Bowler to refactor py2 files containing `print` statements

handle py2/py3 print statement vs function better (via user configurable option)

---

bowler/main.py
makefile

For other projects using Bowler it needs to have the `py.typed` marker file to tell mypy, when run by the other project, that Bowler is typed and to use its annotations
I thought I'd just quickly run mypy on it to make sure it's ok to mark it this way, this reported the following error:
```
bowler/main.py:156: error: Item "_Loader" of "Optional[_Loader]" has no attribute "exec_module"
bowler/main.py:156: error: Item "None" of "Optional[_Loader]" has no attribute "exec_module"
```
I fixed this based on the advice here https://github.com/python/typeshed/issues/2793
Then digging around I saw you're already running mypy in the github CI. The problem seems to be that `make lint` currently runs it as `mypy -m bowler`
This reports:
```
Success: no issues found in 1 source file
``` …

mark bowler package as typed, check all files with mypy

---

.gitignore
bowler/__init__.py
setup.cfg
setup.py

I'm saving `requirements.txt` for another day; I would like to see good minimum versions listed.  These could also move to `pyproject.toml` but I don't currently have that scripted, let me know.

Move to declarative metadata, setuptools_scm
